Repository wecode-bootcamp-korea/49-3rd-DKDK-frontend, pull requests merged in 2023-10, with the labels that each got.

#1 소셜로그인 및 common.scss, axios 추가
  public/images/login_kakao.svg
  public/images/login_naver.svg
  public/images/logo_white.png
  public/index.html
  src/Router.js
  src/index.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginKakao.js
  src/pages/Login/LoginNaver.js
  src/styles/common.scss
Labels: 수정 요청

#3 [style, feat] header 구현 완료
  public/images/logo.png
  public/images/logo_black.png
  public/images/logo_white.png
  src/Router.js
  src/pages/Main/Header/Header.js
  src/pages/Main/Header/Header.scss
  src/pages/Main/Header/LoginGroup/LoginGroup.js
  src/pages/Main/Header/LoginGroup/LoginGroup.scss
  src/styles/mixin.scss
Labels: 멘토 리뷰 요청

#5 Component/signup
  package-lock.json
  package.json
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Login/Login.scss
  src/pages/Login/LoginKakao.js
  src/pages/Login/LoginNaver.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/components/Input/Input.js
  src/pages/Signup/components/Input/Input.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#8 [fix, feat]header scss 수정사항 반영
  src/pages/Main/Header/LoginGroup/LoginGroup.js
  src/pages/Main/Header/LoginGroup/LoginGroup.scss
Labels: 멘토 리뷰 요청

#10 [feat, style]sub navigation 수정사항 반영
  src/pages/Main/SubNav/SubNav.js
  src/pages/Main/SubNav/SubNav.scss
Labels: 멘토 리뷰 요청

#7 style : 마이페이지 초기 화면 UI
  public/data/myPage.json
  public/images/defult_profile.png
  src/Router.js
  src/pages/MyPage/InfoBox.js
  src/pages/MyPage/InfoBox.scss
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.scss
Labels: 수정 요청

#9 Component/modiInfo
  src/Router.js
  src/pages/ModiInfo/ModiInfo.js
  src/pages/ModiInfo/ModiInfo.scss
Labels: 멘토 리뷰 요청

#13 feat : 운동기록 차트 표출 및 회원가입 닉네임 중복 확인
  package-lock.json
  package.json
  public/data/recordData.json
  public/images/like_full.png
  src/Router.js
  src/pages/Record/Record.js
  src/pages/Record/Record.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/components/Input/Input.js
  src/pages/Signup/components/Input/Input.scss
Labels: 멘토 리뷰 요청

#11 [style, feat] 트레이너매칭 페이지 구현 중
  package-lock.json
  package.json
  public/images/subnav.jpg
  src/Router.js
  src/pages/Main/Header/Header.js
  src/pages/Main/SubNav/SubNav.js
  src/pages/Trainers/SelectBox/SelectBox.js
  src/pages/Trainers/SelectBox/SelectBox.scss
  src/pages/Trainers/Trainers.js
  src/pages/Trainers/Trainers.scss
  src/pages/Trainers/TrainersGroup/TrainersGroup.js
  src/pages/Trainers/TrainersGroup/TrainersGroup.scss
Labels: 추가 기능 구현 중

#14 Component/signup
  src/pages/Login/LoginKakao.js
  src/pages/Login/LoginNaver.js
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#16 [style]트레이너 상세 페이지 ui 구현
  src/pages/TrainnerDetail/TrainerDetail.js
  src/pages/TrainnerDetail/TrainerDetail.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#17 [style]trainer 게시물 등록 모달 ui
  src/pages/TrainerRegis/TrainerRegis.js
  src/pages/TrainerRegis/TrainerRegis.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#18 [style, feat]메인페이지 구현 완료
  public/images/banner.jpg
  public/images/sub_banner.jpg
  public/images/sub_banner2.jpg
  public/images/sub_banner3.jpg
  src/data/FOOD_KCAL.js
  src/pages/Main/Banner/Banner.js
  src/pages/Main/Banner/Banner.scss
  src/pages/Main/Bmi/Bmi.js
  src/pages/Main/Bmi/Bmi.scss
  src/pages/Main/Kcal/Kcal.js
  src/pages/Main/Kcal/Kcal.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/SubBanner/SubBanner.js
  src/pages/Main/SubBanner/SubBanner.scss
  src/pages/Main/SubBannerNav/SubBannerNav.js
  src/pages/Main/SubBannerNav/SubBannerNav.scss
Labels: 멘토 리뷰 요청

#20 [fix]subnavigation 예외 페이지 추가
  src/pages/Main/SubNav/SubNav.js
Labels: 멘토 리뷰 요청

#15 Component/user post
  .prettierrc
  package-lock.json
  package.json
  public/images/comment.png
  public/images/like.png
  public/images/running.jpg
  public/images/training.jpg
  public/images/user.png
  src/Router.js
  src/pages/PostDetail/PostDetail.js
  src/pages/PostSignup/PostSignup.js
  src/pages/UserPost/UserPost.js
  src/pages/UserPost/UserPost.scss
Labels: 추가 기능 구현 중

#19 component/PostSignup 글등록페이지 UI 완료
  public/images/filates.jpg
  src/Router.js
  src/pages/PostDetail/PostDetail.scss
  src/pages/PostSignup/PostSignup.js
  src/pages/PostSignup/PostSignup.scss
  src/pages/UserPost/UserPost.js
  src/pages/UserPost/UserPost.scss
Labels: 멘토 리뷰 요청
